// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

plugins {
    `java-library`
    alias(libs.plugins.configuration)
}

projectConfiguration {
    artifactId.set("osv-client-spring-boot-starter")
}

dependencies {
    // library
    api(project(":core"))

    // spring
    api(platform(libs.spring.boot.bom))
    api(libs.spring.boot.starter)
    annotationProcessor(libs.spring.boot.autoconfiguration.processor)
    annotationProcessor(libs.spring.boot.configuration.processor)

    // micrometer
    api(platform(libs.micrometer.bom))
    api(libs.micrometer.core)
}
