// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.client;

import feign.Headers;
import feign.Param;
import feign.RequestLine;
import io.github.primelib.osv.client.models.OsvVulnerability;
import io.github.primelib.osv.client.models.V1BatchQuery;
import io.github.primelib.osv.client.models.V1BatchVulnerabilityList;
import io.github.primelib.osv.client.models.V1Query;
import io.github.primelib.osv.client.models.V1VersionMatchList;
import io.github.primelib.osv.client.models.V1VersionQuery;
import io.github.primelib.osv.client.models.V1VulnerabilityList;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NonNull;

@Generated(value = "io.github.primelib.primecodegen")
public interface OsvClientApi {

    /**
     * PostQueryV1
     * Query vulnerabilities for a particular project at a given commit or
version.
     *
     * API Method: POST /v1/query
     *
     * @param payload 
     */
    @RequestLine("POST /v1/query")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    V1VulnerabilityList postQueryV1(
            @NonNull V1Query payload
    );

    /**
     * PostQuerybatchV1
     * Query vulnerabilities (batched) for given package versions and commits.
This currently allows a maximum of 1000 package versions to be included in a single query.
     *
     * API Method: POST /v1/querybatch
     *
     * @param payload 
     */
    @RequestLine("POST /v1/querybatch")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    V1BatchVulnerabilityList postQuerybatchV1(
            @NonNull V1BatchQuery payload
    );

    /**
     * GetVulnByIDV1
     * Return a `Vulnerability` object for a given OSV ID.
     *
     * API Method: GET /v1/vulns/{id}
     *
     * @param id 
     */
    @RequestLine("GET /v1/vulns/{id}")
    @Headers({
        "Accept: application/json"
    })
    OsvVulnerability getVulnByIdv1(
            @NonNull @Param("id") String id
    );

    /**
     * PostV1ExperimentalDetermineversionV1
     * Determine the version of the provided hash values.
     *
     * API Method: POST /v1experimental/determineversion
     *
     * @param payload 
     */
    @RequestLine("POST /v1experimental/determineversion")
    @Headers({
        "Content-Type: application/json",
        "Accept: application/json"
    })
    V1VersionMatchList postV1ExperimentalDetermineversionV1(
            @NonNull V1VersionQuery payload
    );

}
