// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.client;

import io.github.primelib.osv.client.models.OsvVulnerability;
import io.github.primelib.osv.client.models.V1BatchVulnerabilityList;
import io.github.primelib.osv.client.models.V1VersionMatchList;
import io.github.primelib.osv.client.models.V1VulnerabilityList;
import io.github.primelib.osv.client.operations.GetVulnByIDV1OperationSpec;
import io.github.primelib.osv.client.operations.PostQueryV1OperationSpec;
import io.github.primelib.osv.client.operations.PostQuerybatchV1OperationSpec;
import io.github.primelib.osv.client.operations.PostV1ExperimentalDetermineversionV1OperationSpec;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;

@Generated(value = "io.github.primelib.primecodegen")
public class OsvClientConsumerApi {
    private final OsvClientApi api;

    public OsvClientConsumerApi(OsvClientApi api) {
        this.api = api;
    }


    /**
     * PostQueryV1
     * Query vulnerabilities for a particular project at a given commit or
version.
     *
     * API Method: POST /v1/query
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     * </ul>
    */
    public V1VulnerabilityList postQueryV1(Consumer<PostQueryV1OperationSpec> spec) {
        PostQueryV1OperationSpec r = new PostQueryV1OperationSpec(spec);
        return api.postQueryV1(r.payload());
    }

    /**
     * PostQuerybatchV1
     * Query vulnerabilities (batched) for given package versions and commits.
This currently allows a maximum of 1000 package versions to be included in a single query.
     *
     * API Method: POST /v1/querybatch
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     * </ul>
    */
    public V1BatchVulnerabilityList postQuerybatchV1(Consumer<PostQuerybatchV1OperationSpec> spec) {
        PostQuerybatchV1OperationSpec r = new PostQuerybatchV1OperationSpec(spec);
        return api.postQuerybatchV1(r.payload());
    }

    /**
     * GetVulnByIDV1
     * Return a `Vulnerability` object for a given OSV ID.
     *
     * API Method: GET /v1/vulns/{id}
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>id: </li>
     * </ul>
    */
    public OsvVulnerability getVulnByIdv1(Consumer<GetVulnByIDV1OperationSpec> spec) {
        GetVulnByIDV1OperationSpec r = new GetVulnByIDV1OperationSpec(spec);
        return api.getVulnByIdv1(r.id());
    }

    /**
     * PostV1ExperimentalDetermineversionV1
     * Determine the version of the provided hash values.
     *
     * API Method: POST /v1experimental/determineversion
     *
     * @param spec a consumer that creates the payload for this operation. Supports the following properties:
     * <ul>
     *   <li>payload: </li>
     * </ul>
    */
    public V1VersionMatchList postV1ExperimentalDetermineversionV1(Consumer<PostV1ExperimentalDetermineversionV1OperationSpec> spec) {
        PostV1ExperimentalDetermineversionV1OperationSpec r = new PostV1ExperimentalDetermineversionV1OperationSpec(spec);
        return api.postV1ExperimentalDetermineversionV1(r.payload());
    }

}
