// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

plugins {
    alias(libs.plugins.configuration)
}

subprojects {
    apply(plugin = "me.philippheuer.configuration")

    projectConfiguration {
        type.set(me.philippheuer.projectcfg.domain.ProjectType.LIBRARY)
        javaVersion.set(JavaVersion.VERSION_17)
        artifactGroupId.set("io.github.primelib")
        artifactDisplayName.set("OSV Client")
        artifactDescription.set("Unofficial API client generated from the osv.dev API specification.")
        javadocLint.set(listOf("none"))

        pom = { pom ->
            pom.url.set("https://https://github.com/primelib/osv-client")
            pom.issueManagement {
                system.set("GitHub")
                url.set("https://https://github.com/primelib/osv-client/issues")
            }
            pom.developers {
                developer {
                  id.set("PrimeCodeGen")
                  name.set("PrimeLib PrimeCodeGen")
                  roles.addAll("maintainer")
                }
            }
            pom.licenses {
                license {
                    name.set("MIT")
                    distribution.set("repo")
                    url.set("https://github.com/primelib/osv-client/blob/main/LICENSE")
                }
            }
            pom.scm {
                connection.set("scm:git:git://https://github.com/primelib/osv-client.git")
                developerConnection.set("scm:git:git://https://github.com/primelib/osv-client.git")
                url.set("https://https://github.com/primelib/osv-client")
            }
        }
    }
}
