// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "osv-client"

include(
    "core",
    "spring"
)
