// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * OsvCreditType
 *
 */
@JsonTypeName("OsvCreditType")
@Generated(value = "io.github.primelib.primecodegen")
public enum OsvCreditType {
    ANALYST("ANALYST"),
    COORDINATOR("COORDINATOR"),
    FINDER("FINDER"),
    OTHER("OTHER"),
    REMEDIATION_DEVELOPER("REMEDIATION_DEVELOPER"),
    REMEDIATION_REVIEWER("REMEDIATION_REVIEWER"),
    REMEDIATION_VERIFIER("REMEDIATION_VERIFIER"),
    REPORTER("REPORTER"),
    SPONSOR("SPONSOR"),
    TOOL("TOOL"),
    UNSPECIFIED("UNSPECIFIED"),
    ;

    private final String value;

    OsvCreditType(String value) {
        this.value = value;
    }
}
