// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * OsvRangeType
 * <p>
 * Type of the version information.
 *
 */
@JsonTypeName("OsvRangeType")
@Generated(value = "io.github.primelib.primecodegen")
public enum OsvRangeType {
    ECOSYSTEM("ECOSYSTEM"),
    GIT("GIT"),
    SEMVER("SEMVER"),
    UNSPECIFIED("UNSPECIFIED"),
    ;

    private final String value;

    OsvRangeType(String value) {
        this.value = value;
    }
}
