// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * ProtobufNullValue
 * <p>
 * `NullValue` is a singleton enumeration to represent the null value for the
 * `Value` type union.
 * 
 *  The JSON representation for `NullValue` is JSON `null`.
 * 
 *  - NULL_VALUE: Null value.
 *
 */
@JsonTypeName("ProtobufNullValue")
@Generated(value = "io.github.primelib.primecodegen")
public enum ProtobufNullValue {
    NULL_VALUE("NULL_VALUE"),
    ;

    private final String value;

    ProtobufNullValue(String value) {
        this.value = value;
    }
}
