// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * V1VersionRepositoryInformationRepoType
 *
 */
@JsonTypeName("V1VersionRepositoryInformationRepoType")
@Generated(value = "io.github.primelib.primecodegen")
public enum V1VersionRepositoryInformationRepoType {
    GIT("GIT"),
    UNSPECIFIED("UNSPECIFIED"),
    ;

    private final String value;

    V1VersionRepositoryInformationRepoType(String value) {
        this.value = value;
    }
}
