// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * OsvEvent
 * <p>
 * Version events.
 *
 */
@JsonTypeName("OsvEvent")
@JsonPropertyOrder({
    "introduced",
    "fixed",
    "limit",
    "lastAffected"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OsvEvent {

    /**
     * The earliest version/commit where this vulnerability
was introduced in.
     */
    @JsonProperty("introduced")
    protected String introduced;

    /**
     * The version/commit that this vulnerability was fixed in.
     */
    @JsonProperty("fixed")
    protected String fixed;

    /**
     * The limit to apply to the range.
     */
    @JsonProperty("limit")
    protected String limit;

    /**
     * The last affected version.
     */
    @JsonProperty("lastAffected")
    protected String lastAffected;

    /**
     * Constructs a validated instance of {@link OsvEvent}.
     *
     * @param spec the specification to process
     */
    public OsvEvent(Consumer<OsvEvent> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected OsvEvent() {
    }

    /**
     * Constructs a validated instance of {@link OsvEvent}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OsvEvent(Consumer)} instead.
     * @param introduced The earliest version/commit where this vulnerability
was introduced in.
     * @param fixed The version/commit that this vulnerability was fixed in.
     * @param limit The limit to apply to the range.
     * @param lastAffected The last affected version.
     */
    @ApiStatus.Internal
    public OsvEvent(String introduced, String fixed, String limit, String lastAffected) {
        this.introduced = introduced;
        this.fixed = fixed;
        this.limit = limit;
        this.lastAffected = lastAffected;
    }


    /**
     * Fluent getter for introduced.
     * <p>
     * The earliest version/commit where this vulnerability
     * was introduced in.
     *
     * @return introduced
     */
    public String introduced() {
        return this.introduced;
    }

    /**
     * Fluent setter for introduced.
     * <p>
     * The earliest version/commit where this vulnerability
     * was introduced in.
     *
     * @param introduced introduced
     * @return this
     */
    public OsvEvent introduced(String introduced) {
        this.introduced = introduced;
        return this;
    }

    /**
     * Gets the value of introduced.
     * <p>
     * The earliest version/commit where this vulnerability
     * was introduced in.
     *
     * @return introduced
     */
    @JsonProperty("introduced")
    public String getIntroduced() {
        return this.introduced;
    }

    /**
     * Sets the value of introduced.
     * <p>
     * The earliest version/commit where this vulnerability
     * was introduced in.
     *
     * @param introduced introduced
     */
    public void setIntroduced(String introduced) {
        this.introduced = introduced;
    }
    /**
     * Fluent getter for fixed.
     * <p>
     * The version/commit that this vulnerability was fixed in.
     *
     * @return fixed
     */
    public String fixed() {
        return this.fixed;
    }

    /**
     * Fluent setter for fixed.
     * <p>
     * The version/commit that this vulnerability was fixed in.
     *
     * @param fixed fixed
     * @return this
     */
    public OsvEvent fixed(String fixed) {
        this.fixed = fixed;
        return this;
    }

    /**
     * Gets the value of fixed.
     * <p>
     * The version/commit that this vulnerability was fixed in.
     *
     * @return fixed
     */
    @JsonProperty("fixed")
    public String getFixed() {
        return this.fixed;
    }

    /**
     * Sets the value of fixed.
     * <p>
     * The version/commit that this vulnerability was fixed in.
     *
     * @param fixed fixed
     */
    public void setFixed(String fixed) {
        this.fixed = fixed;
    }
    /**
     * Fluent getter for limit.
     * <p>
     * The limit to apply to the range.
     *
     * @return limit
     */
    public String limit() {
        return this.limit;
    }

    /**
     * Fluent setter for limit.
     * <p>
     * The limit to apply to the range.
     *
     * @param limit limit
     * @return this
     */
    public OsvEvent limit(String limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Gets the value of limit.
     * <p>
     * The limit to apply to the range.
     *
     * @return limit
     */
    @JsonProperty("limit")
    public String getLimit() {
        return this.limit;
    }

    /**
     * Sets the value of limit.
     * <p>
     * The limit to apply to the range.
     *
     * @param limit limit
     */
    public void setLimit(String limit) {
        this.limit = limit;
    }
    /**
     * Fluent getter for lastAffected.
     * <p>
     * The last affected version.
     *
     * @return lastAffected
     */
    public String lastAffected() {
        return this.lastAffected;
    }

    /**
     * Fluent setter for lastAffected.
     * <p>
     * The last affected version.
     *
     * @param lastAffected lastAffected
     * @return this
     */
    public OsvEvent lastAffected(String lastAffected) {
        this.lastAffected = lastAffected;
        return this;
    }

    /**
     * Gets the value of lastAffected.
     * <p>
     * The last affected version.
     *
     * @return lastAffected
     */
    @JsonProperty("lastAffected")
    public String getLastAffected() {
        return this.lastAffected;
    }

    /**
     * Sets the value of lastAffected.
     * <p>
     * The last affected version.
     *
     * @param lastAffected lastAffected
     */
    public void setLastAffected(String lastAffected) {
        this.lastAffected = lastAffected;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OsvEvent that = (OsvEvent) o;
        return
            Objects.equals(this.introduced, that.introduced) &&
            Objects.equals(this.fixed, that.fixed) &&
            Objects.equals(this.limit, that.limit) &&
            Objects.equals(this.lastAffected, that.lastAffected);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.introduced, 
            this.fixed, 
            this.limit, 
            this.lastAffected
        );
    }

    @Override
    public String toString() {
        return "OsvEvent{" +
            "introduced=" + introduced + ", " + 
            "fixed=" + fixed + ", " + 
            "limit=" + limit + ", " + 
            "lastAffected=" + lastAffected +
            "}";
    }
}
