// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * OsvSeverity
 *
 */
@JsonTypeName("OsvSeverity")
@JsonPropertyOrder({
    "type",
    "score"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OsvSeverity {

    /**
     * Type of the severity.
     */
    @JsonProperty("type")
    protected String type;

    /**
     * The quantitative score.
     */
    @JsonProperty("score")
    protected String score;

    /**
     * Constructs a validated instance of {@link OsvSeverity}.
     *
     * @param spec the specification to process
     */
    public OsvSeverity(Consumer<OsvSeverity> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected OsvSeverity() {
    }

    /**
     * Constructs a validated instance of {@link OsvSeverity}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OsvSeverity(Consumer)} instead.
     * @param type Type of the severity.
     * @param score The quantitative score.
     */
    @ApiStatus.Internal
    public OsvSeverity(String type, String score) {
        this.type = type;
        this.score = score;
    }


    /**
     * Fluent getter for type.
     * <p>
     * Type of the severity.
     *
     * @return type
     */
    public String type() {
        return this.type;
    }

    /**
     * Fluent setter for type.
     * <p>
     * Type of the severity.
     *
     * @param type type
     * @return this
     */
    public OsvSeverity type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Gets the value of type.
     * <p>
     * Type of the severity.
     *
     * @return type
     */
    @JsonProperty("type")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of type.
     * <p>
     * Type of the severity.
     *
     * @param type type
     */
    public void setType(String type) {
        this.type = type;
    }
    /**
     * Fluent getter for score.
     * <p>
     * The quantitative score.
     *
     * @return score
     */
    public String score() {
        return this.score;
    }

    /**
     * Fluent setter for score.
     * <p>
     * The quantitative score.
     *
     * @param score score
     * @return this
     */
    public OsvSeverity score(String score) {
        this.score = score;
        return this;
    }

    /**
     * Gets the value of score.
     * <p>
     * The quantitative score.
     *
     * @return score
     */
    @JsonProperty("score")
    public String getScore() {
        return this.score;
    }

    /**
     * Sets the value of score.
     * <p>
     * The quantitative score.
     *
     * @param score score
     */
    public void setScore(String score) {
        this.score = score;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OsvSeverity that = (OsvSeverity) o;
        return
            Objects.equals(this.type, that.type) &&
            Objects.equals(this.score, that.score);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.type, 
            this.score
        );
    }

    @Override
    public String toString() {
        return "OsvSeverity{" +
            "type=" + type + ", " + 
            "score=" + score +
            "}";
    }
}
