// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * RpcStatus
 *
 */
@JsonTypeName("RpcStatus")
@JsonPropertyOrder({
    "code",
    "message",
    "details"
})
@Generated(value = "io.github.primelib.primecodegen")
public class RpcStatus {

    @JsonProperty("code")
    protected Integer code;

    @JsonProperty("message")
    protected String message;

    @JsonProperty("details")
    protected List<ProtobufAny> details;

    /**
     * Constructs a validated instance of {@link RpcStatus}.
     *
     * @param spec the specification to process
     */
    public RpcStatus(Consumer<RpcStatus> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected RpcStatus() {
    }

    /**
     * Constructs a validated instance of {@link RpcStatus}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #RpcStatus(Consumer)} instead.
     * @param code code
     * @param message message
     * @param details details
     */
    @ApiStatus.Internal
    public RpcStatus(Integer code, String message, List<ProtobufAny> details) {
        this.code = code;
        this.message = message;
        this.details = details;
    }


    /**
     * Fluent getter for code.
     *
     * @return code
     */
    public Integer code() {
        return this.code;
    }

    /**
     * Fluent setter for code.
     *
     * @param code code
     * @return this
     */
    public RpcStatus code(Integer code) {
        this.code = code;
        return this;
    }

    /**
     * Gets the value of code.
     *
     * @return code
     */
    @JsonProperty("code")
    public Integer getCode() {
        return this.code;
    }

    /**
     * Sets the value of code.
     *
     * @param code code
     */
    public void setCode(Integer code) {
        this.code = code;
    }
    /**
     * Fluent getter for message.
     *
     * @return message
     */
    public String message() {
        return this.message;
    }

    /**
     * Fluent setter for message.
     *
     * @param message message
     * @return this
     */
    public RpcStatus message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Gets the value of message.
     *
     * @return message
     */
    @JsonProperty("message")
    public String getMessage() {
        return this.message;
    }

    /**
     * Sets the value of message.
     *
     * @param message message
     */
    public void setMessage(String message) {
        this.message = message;
    }
    /**
     * Fluent getter for details.
     *
     * @return details
     */
    public List<ProtobufAny> details() {
        return this.details;
    }

    /**
     * Fluent setter for details.
     *
     * @param details details
     * @return this
     */
    public RpcStatus details(List<ProtobufAny> details) {
        this.details = details;
        return this;
    }

    /**
     * Gets the value of details.
     *
     * @return details
     */
    @JsonProperty("details")
    public List<ProtobufAny> getDetails() {
        return this.details;
    }

    /**
     * Sets the value of details.
     *
     * @param details details
     */
    public void setDetails(List<ProtobufAny> details) {
        this.details = details;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RpcStatus that = (RpcStatus) o;
        return
            Objects.equals(this.code, that.code) &&
            Objects.equals(this.message, that.message) &&
            Objects.equals(this.details, that.details);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.code, 
            this.message, 
            this.details
        );
    }

    @Override
    public String toString() {
        return "RpcStatus{" +
            "code=" + code + ", " + 
            "message=" + message + ", " + 
            "details=" + details +
            "}";
    }
}
