// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Arrays;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * V1FileHash
 * <p>
 * Information about the files in the repository
 * to identify the version.
 *
 */
@JsonTypeName("V1FileHash")
@JsonPropertyOrder({
    "filePath",
    "hashType",
    "hash"
})
@Generated(value = "io.github.primelib.primecodegen")
public class V1FileHash {

    /**
     * The file path inside the repository, relative to the repository root.
     */
    @JsonProperty("filePath")
    protected String filePath;

    @JsonProperty("hashType")
    protected String hashType;

    @JsonProperty("hash")
    protected Byte[] hash;

    /**
     * Constructs a validated instance of {@link V1FileHash}.
     *
     * @param spec the specification to process
     */
    public V1FileHash(Consumer<V1FileHash> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected V1FileHash() {
    }

    /**
     * Constructs a validated instance of {@link V1FileHash}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #V1FileHash(Consumer)} instead.
     * @param filePath The file path inside the repository, relative to the repository root.
     * @param hashType hashType
     * @param hash hash
     */
    @ApiStatus.Internal
    public V1FileHash(String filePath, String hashType, Byte[] hash) {
        this.filePath = filePath;
        this.hashType = hashType;
        this.hash = hash;
    }


    /**
     * Fluent getter for filePath.
     * <p>
     * The file path inside the repository, relative to the repository root.
     *
     * @return filePath
     */
    public String filePath() {
        return this.filePath;
    }

    /**
     * Fluent setter for filePath.
     * <p>
     * The file path inside the repository, relative to the repository root.
     *
     * @param filePath filePath
     * @return this
     */
    public V1FileHash filePath(String filePath) {
        this.filePath = filePath;
        return this;
    }

    /**
     * Gets the value of filePath.
     * <p>
     * The file path inside the repository, relative to the repository root.
     *
     * @return filePath
     */
    @JsonProperty("filePath")
    public String getFilePath() {
        return this.filePath;
    }

    /**
     * Sets the value of filePath.
     * <p>
     * The file path inside the repository, relative to the repository root.
     *
     * @param filePath filePath
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    /**
     * Fluent getter for hashType.
     *
     * @return hashType
     */
    public String hashType() {
        return this.hashType;
    }

    /**
     * Fluent setter for hashType.
     *
     * @param hashType hashType
     * @return this
     */
    public V1FileHash hashType(String hashType) {
        this.hashType = hashType;
        return this;
    }

    /**
     * Gets the value of hashType.
     *
     * @return hashType
     */
    @JsonProperty("hashType")
    public String getHashType() {
        return this.hashType;
    }

    /**
     * Sets the value of hashType.
     *
     * @param hashType hashType
     */
    public void setHashType(String hashType) {
        this.hashType = hashType;
    }
    /**
     * Fluent getter for hash.
     *
     * @return hash
     */
    public Byte[] hash() {
        return this.hash;
    }

    /**
     * Fluent setter for hash.
     *
     * @param hash hash
     * @return this
     */
    public V1FileHash hash(Byte[] hash) {
        this.hash = hash;
        return this;
    }

    /**
     * Gets the value of hash.
     *
     * @return hash
     */
    @JsonProperty("hash")
    public Byte[] getHash() {
        return this.hash;
    }

    /**
     * Sets the value of hash.
     *
     * @param hash hash
     */
    public void setHash(Byte[] hash) {
        this.hash = hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        V1FileHash that = (V1FileHash) o;
        return
            Objects.equals(this.filePath, that.filePath) &&
            Objects.equals(this.hashType, that.hashType) &&
            Objects.equals(this.hash, that.hash);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.filePath, 
            this.hashType, 
            this.hash
        );
    }

    @Override
    public String toString() {
        return "V1FileHash{" +
            "filePath=" + filePath + ", " + 
            "hashType=" + hashType + ", " + 
            "hash=" + Arrays.deepToString(this.hash) +
            "}";
    }
}
