// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * V1VersionMatchList
 * <p>
 * Result of DetmineVersion.
 *
 */
@JsonTypeName("V1VersionMatchList")
@JsonPropertyOrder({
    "matches"
})
@Generated(value = "io.github.primelib.primecodegen")
public class V1VersionMatchList {

    @JsonProperty("matches")
    protected List<V1VersionMatch> matches;

    /**
     * Constructs a validated instance of {@link V1VersionMatchList}.
     *
     * @param spec the specification to process
     */
    public V1VersionMatchList(Consumer<V1VersionMatchList> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected V1VersionMatchList() {
    }

    /**
     * Constructs a validated instance of {@link V1VersionMatchList}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #V1VersionMatchList(Consumer)} instead.
     * @param matches matches
     */
    @ApiStatus.Internal
    public V1VersionMatchList(List<V1VersionMatch> matches) {
        this.matches = matches;
    }


    /**
     * Fluent getter for matches.
     *
     * @return matches
     */
    public List<V1VersionMatch> matches() {
        return this.matches;
    }

    /**
     * Fluent setter for matches.
     *
     * @param matches matches
     * @return this
     */
    public V1VersionMatchList matches(List<V1VersionMatch> matches) {
        this.matches = matches;
        return this;
    }

    /**
     * Gets the value of matches.
     *
     * @return matches
     */
    @JsonProperty("matches")
    public List<V1VersionMatch> getMatches() {
        return this.matches;
    }

    /**
     * Sets the value of matches.
     *
     * @param matches matches
     */
    public void setMatches(List<V1VersionMatch> matches) {
        this.matches = matches;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        V1VersionMatchList that = (V1VersionMatchList) o;
        return
            Objects.equals(this.matches, that.matches);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.matches
        );
    }

    @Override
    public String toString() {
        return "V1VersionMatchList{" +
            "matches=" + matches +
            "}";
    }
}
