// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * OsvReferenceType
 *
 */
@JsonTypeName("OsvReferenceType")
@Generated(value = "io.github.primelib.primecodegen")
public enum OsvReferenceType {
    ADVISORY("ADVISORY"),
    ARTICLE("ARTICLE"),
    EVIDENCE("EVIDENCE"),
    FIX("FIX"),
    NONE("NONE"),
    PACKAGE("PACKAGE"),
    REPORT("REPORT"),
    WEB("WEB"),
    ;

    private final String value;

    OsvReferenceType(String value) {
        this.value = value;
    }
}
