// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * OsvSeverityType
 * <p>
 * Type of the severity.
 *
 */
@JsonTypeName("OsvSeverityType")
@Generated(value = "io.github.primelib.primecodegen")
public enum OsvSeverityType {
    CVSS_V_2("CVSS_V2"),
    CVSS_V_3("CVSS_V3"),
    CVSS_V_4("CVSS_V4"),
    UNSPECIFIED("UNSPECIFIED"),
    ;

    private final String value;

    OsvSeverityType(String value) {
        this.value = value;
    }
}
