// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv.client.spring;

import io.github.primelib.osv.client.OsvClientFactory;
import io.github.primelib.osv.client.client.OsvClientApi;
import io.github.primelib.osv.client.client.OsvClientConsumerApi;
import io.github.primelib.primecodegenlib.java.feign.common.api.AuthMethod;
import io.github.primelib.primecodegenlib.java.feign.common.auth.BearerAuthSpec;
import io.github.primelib.primecodegenlib.java.feign.common.auth.OAuth2ClientCredentialsAuthSpec;
import io.github.primelib.primecodegenlib.java.feign.common.auth.OAuth2UserCredentialsAuthSpec;
import io.micrometer.core.instrument.MeterRegistry;
import java.util.List;
import javax.annotation.processing.Generated;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;

@AutoConfiguration
@EnableConfigurationProperties(OsvClientSpringAutoConfiguration.Properties.class)
@ConditionalOnProperty(name = "osv-client.url", matchIfMissing = false)
@Slf4j
@Generated(value = "io.github.primelib.primecodegen")
public class OsvClientSpringAutoConfiguration {
    private final Properties properties;
    private final MeterRegistry meterRegistry;

    public OsvClientSpringAutoConfiguration(Properties properties, MeterRegistry meterRegistry) {
        this.properties = properties;
        this.meterRegistry = meterRegistry;
    }

    @Bean
    @Primary
    public OsvClientApi OsvClientApi() {
        return OsvClientFactory.create(spec -> {
            spec.api(OsvClientApi.class);
            spec.baseUrl(properties.getUrl());
            spec.auth(buildAuthSpecs(properties));
            if (properties.getInsecure() != null) {
                spec.insecure(properties.getInsecure());
            }
            if (properties.getBackendName() != null && !properties.getBackendName().isEmpty()) {
                spec.backendName(properties.getBackendName());
            }
            if (properties.getLogLevel() != null && !properties.getLogLevel().isEmpty()) {
                spec.logLevel(properties.getLogLevel());
            }
            spec.meterRegistry(meterRegistry);
        });
    }

    @Bean
    @Primary
    public OsvClientConsumerApi OsvClientConsumerApi() {
        return OsvClientFactory.create(spec -> {
            spec.api(OsvClientConsumerApi.class);
            spec.baseUrl(properties.getUrl());
            spec.auth(buildAuthSpecs(properties));
            if (properties.getInsecure() != null) {
                spec.insecure(properties.getInsecure());
            }
            if (properties.getBackendName() != null && !properties.getBackendName().isEmpty()) {
                spec.backendName(properties.getBackendName());
            }
            if (properties.getLogLevel() != null && !properties.getLogLevel().isEmpty()) {
                spec.logLevel(properties.getLogLevel());
            }
            spec.meterRegistry(meterRegistry);
        });
    }

    

    private List<AuthMethod> buildAuthSpecs(Properties props) {
        if (props.getAuth() == null || props.getAuth().getType() == null) {
            return null;
        }

        switch (props.getAuth().getType()) {
            case "oauth2-user":
                return List.of(new OAuth2UserCredentialsAuthSpec(auth -> {
                    auth.tokenEndpoint(props.getAuth().getTokenEndpoint());
                    auth.clientId(props.getAuth().getClientId());
                    auth.clientSecret(props.getAuth().getClientSecret());
                    auth.username(props.getAuth().getUsername());
                    auth.password(props.getAuth().getPassword());
                }));
            case "oauth2-client":
                return List.of(new OAuth2ClientCredentialsAuthSpec(auth -> {
                    auth.tokenEndpoint(props.getAuth().getTokenEndpoint());
                    auth.clientId(props.getAuth().getClientId());
                    auth.clientSecret(props.getAuth().getClientSecret());
                }));
            case "bearer":
                return List.of(new BearerAuthSpec(auth -> {
                    if (props.getAuth().getTokenPropertyKey() != null && !props.getAuth().getTokenPropertyKey().isEmpty()) {
                        auth.propertyKey(props.getAuth().getTokenPropertyKey());
                    }
                    if (props.getAuth().getTokenValueTemplate() != null && !props.getAuth().getTokenValueTemplate().isEmpty()) {
                        auth.propertyKey(props.getAuth().getTokenValueTemplate());
                    }
                    auth.propertyKey(props.getAuth().getToken());
                }));
            default:
                return null;
        }
    }

    @Data
    @ConfigurationProperties(prefix = "osv-client")
    public static class Properties {
        private String url = "";
        private String backendName = "";
        private String logLevel = "";
        private Boolean insecure = false;
        private Auth auth;

        @Data
        public static class Auth {
            /**
             * Type of authentication.
             * Supported values: "oauth2-user", "oauth2-client", "bearer".
             */
            private String type;
            /**
             * Full token endpoint URL
             */
            private String tokenEndpoint;
            private String clientId;
            private String clientSecret;
            private String username;
            private String password;
            private String token;
            /**
             * Header key to pass the token in (used by BearerAuthSpec).
             */
            private String tokenPropertyKey;
            /**
             * Template to generate token value (used by BearerAuthSpec).
             */
            private String tokenValueTemplate;
        }
    }
}
