// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * OsvAffected
 * <p>
 * Affected versions and commits.
 *
 */
@JsonTypeName("OsvAffected")
@JsonPropertyOrder({
    "packageProp",
    "ranges",
    "versions",
    "ecosystemSpecific",
    "databaseSpecific",
    "severity"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OsvAffected {

    /**
     * Package information and version.
     */
    @JsonProperty("package")
    protected OsvPackage packageProp;

    /**
     * Required. Range information.
     */
    @JsonProperty("ranges")
    protected List<OsvRange> ranges;

    /**
     * Optional. List of affected versions.
     */
    @JsonProperty("versions")
    protected List<String> versions;

    /**
     * Optional. JSON object holding additional information about the
vulnerability as defined by the ecosystem for which the record applies.
     */
    @JsonProperty("ecosystemSpecific")
    protected Object ecosystemSpecific;

    /**
     * Optional. JSON object holding additional information about the
vulnerability as defined by the database for which the record applies.
     */
    @JsonProperty("databaseSpecific")
    protected Object databaseSpecific;

    /**
     * Optional. Severity of the vulnerability for this package.
     */
    @JsonProperty("severity")
    protected List<OsvSeverity> severity;

    /**
     * Constructs a validated instance of {@link OsvAffected}.
     *
     * @param spec the specification to process
     */
    public OsvAffected(Consumer<OsvAffected> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected OsvAffected() {
    }

    /**
     * Constructs a validated instance of {@link OsvAffected}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OsvAffected(Consumer)} instead.
     * @param packageProp Package information and version.
     * @param ranges Required. Range information.
     * @param versions Optional. List of affected versions.
     * @param ecosystemSpecific Optional. JSON object holding additional information about the
vulnerability as defined by the ecosystem for which the record applies.
     * @param databaseSpecific Optional. JSON object holding additional information about the
vulnerability as defined by the database for which the record applies.
     * @param severity Optional. Severity of the vulnerability for this package.
     */
    @ApiStatus.Internal
    public OsvAffected(OsvPackage packageProp, List<OsvRange> ranges, List<String> versions, Object ecosystemSpecific, Object databaseSpecific, List<OsvSeverity> severity) {
        this.packageProp = packageProp;
        this.ranges = ranges;
        this.versions = versions;
        this.ecosystemSpecific = ecosystemSpecific;
        this.databaseSpecific = databaseSpecific;
        this.severity = severity;
    }


    /**
     * Fluent getter for packageProp.
     * <p>
     * Package information and version.
     *
     * @return packageProp
     */
    public OsvPackage packageProp() {
        return this.packageProp;
    }

    /**
     * Fluent setter for packageProp.
     * <p>
     * Package information and version.
     *
     * @param packageProp packageProp
     * @return this
     */
    public OsvAffected packageProp(OsvPackage packageProp) {
        this.packageProp = packageProp;
        return this;
    }

    /**
     * Gets the value of packageProp.
     * <p>
     * Package information and version.
     *
     * @return packageProp
     */
    @JsonProperty("package")
    public OsvPackage getPackageProp() {
        return this.packageProp;
    }

    /**
     * Sets the value of packageProp.
     * <p>
     * Package information and version.
     *
     * @param packageProp packageProp
     */
    public void setPackageProp(OsvPackage packageProp) {
        this.packageProp = packageProp;
    }
    /**
     * Fluent getter for ranges.
     * <p>
     * Required. Range information.
     *
     * @return ranges
     */
    public List<OsvRange> ranges() {
        return this.ranges;
    }

    /**
     * Fluent setter for ranges.
     * <p>
     * Required. Range information.
     *
     * @param ranges ranges
     * @return this
     */
    public OsvAffected ranges(List<OsvRange> ranges) {
        this.ranges = ranges;
        return this;
    }

    /**
     * Gets the value of ranges.
     * <p>
     * Required. Range information.
     *
     * @return ranges
     */
    @JsonProperty("ranges")
    public List<OsvRange> getRanges() {
        return this.ranges;
    }

    /**
     * Sets the value of ranges.
     * <p>
     * Required. Range information.
     *
     * @param ranges ranges
     */
    public void setRanges(List<OsvRange> ranges) {
        this.ranges = ranges;
    }
    /**
     * Fluent getter for versions.
     * <p>
     * Optional. List of affected versions.
     *
     * @return versions
     */
    public List<String> versions() {
        return this.versions;
    }

    /**
     * Fluent setter for versions.
     * <p>
     * Optional. List of affected versions.
     *
     * @param versions versions
     * @return this
     */
    public OsvAffected versions(List<String> versions) {
        this.versions = versions;
        return this;
    }

    /**
     * Gets the value of versions.
     * <p>
     * Optional. List of affected versions.
     *
     * @return versions
     */
    @JsonProperty("versions")
    public List<String> getVersions() {
        return this.versions;
    }

    /**
     * Sets the value of versions.
     * <p>
     * Optional. List of affected versions.
     *
     * @param versions versions
     */
    public void setVersions(List<String> versions) {
        this.versions = versions;
    }
    /**
     * Fluent getter for ecosystemSpecific.
     * <p>
     * Optional. JSON object holding additional information about the
     * vulnerability as defined by the ecosystem for which the record applies.
     *
     * @return ecosystemSpecific
     */
    public Object ecosystemSpecific() {
        return this.ecosystemSpecific;
    }

    /**
     * Fluent setter for ecosystemSpecific.
     * <p>
     * Optional. JSON object holding additional information about the
     * vulnerability as defined by the ecosystem for which the record applies.
     *
     * @param ecosystemSpecific ecosystemSpecific
     * @return this
     */
    public OsvAffected ecosystemSpecific(Object ecosystemSpecific) {
        this.ecosystemSpecific = ecosystemSpecific;
        return this;
    }

    /**
     * Gets the value of ecosystemSpecific.
     * <p>
     * Optional. JSON object holding additional information about the
     * vulnerability as defined by the ecosystem for which the record applies.
     *
     * @return ecosystemSpecific
     */
    @JsonProperty("ecosystemSpecific")
    public Object getEcosystemSpecific() {
        return this.ecosystemSpecific;
    }

    /**
     * Sets the value of ecosystemSpecific.
     * <p>
     * Optional. JSON object holding additional information about the
     * vulnerability as defined by the ecosystem for which the record applies.
     *
     * @param ecosystemSpecific ecosystemSpecific
     */
    public void setEcosystemSpecific(Object ecosystemSpecific) {
        this.ecosystemSpecific = ecosystemSpecific;
    }
    /**
     * Fluent getter for databaseSpecific.
     * <p>
     * Optional. JSON object holding additional information about the
     * vulnerability as defined by the database for which the record applies.
     *
     * @return databaseSpecific
     */
    public Object databaseSpecific() {
        return this.databaseSpecific;
    }

    /**
     * Fluent setter for databaseSpecific.
     * <p>
     * Optional. JSON object holding additional information about the
     * vulnerability as defined by the database for which the record applies.
     *
     * @param databaseSpecific databaseSpecific
     * @return this
     */
    public OsvAffected databaseSpecific(Object databaseSpecific) {
        this.databaseSpecific = databaseSpecific;
        return this;
    }

    /**
     * Gets the value of databaseSpecific.
     * <p>
     * Optional. JSON object holding additional information about the
     * vulnerability as defined by the database for which the record applies.
     *
     * @return databaseSpecific
     */
    @JsonProperty("databaseSpecific")
    public Object getDatabaseSpecific() {
        return this.databaseSpecific;
    }

    /**
     * Sets the value of databaseSpecific.
     * <p>
     * Optional. JSON object holding additional information about the
     * vulnerability as defined by the database for which the record applies.
     *
     * @param databaseSpecific databaseSpecific
     */
    public void setDatabaseSpecific(Object databaseSpecific) {
        this.databaseSpecific = databaseSpecific;
    }
    /**
     * Fluent getter for severity.
     * <p>
     * Optional. Severity of the vulnerability for this package.
     *
     * @return severity
     */
    public List<OsvSeverity> severity() {
        return this.severity;
    }

    /**
     * Fluent setter for severity.
     * <p>
     * Optional. Severity of the vulnerability for this package.
     *
     * @param severity severity
     * @return this
     */
    public OsvAffected severity(List<OsvSeverity> severity) {
        this.severity = severity;
        return this;
    }

    /**
     * Gets the value of severity.
     * <p>
     * Optional. Severity of the vulnerability for this package.
     *
     * @return severity
     */
    @JsonProperty("severity")
    public List<OsvSeverity> getSeverity() {
        return this.severity;
    }

    /**
     * Sets the value of severity.
     * <p>
     * Optional. Severity of the vulnerability for this package.
     *
     * @param severity severity
     */
    public void setSeverity(List<OsvSeverity> severity) {
        this.severity = severity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OsvAffected that = (OsvAffected) o;
        return
            Objects.equals(this.packageProp, that.packageProp) &&
            Objects.equals(this.ranges, that.ranges) &&
            Objects.equals(this.versions, that.versions) &&
            Objects.equals(this.ecosystemSpecific, that.ecosystemSpecific) &&
            Objects.equals(this.databaseSpecific, that.databaseSpecific) &&
            Objects.equals(this.severity, that.severity);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.packageProp, 
            this.ranges, 
            this.versions, 
            this.ecosystemSpecific, 
            this.databaseSpecific, 
            this.severity
        );
    }

    @Override
    public String toString() {
        return "OsvAffected{" +
            "packageProp=" + packageProp + ", " + 
            "ranges=" + ranges + ", " + 
            "versions=" + versions + ", " + 
            "ecosystemSpecific=" + ecosystemSpecific + ", " + 
            "databaseSpecific=" + databaseSpecific + ", " + 
            "severity=" + severity +
            "}";
    }
}
