// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * OsvCredit
 *
 */
@JsonTypeName("OsvCredit")
@JsonPropertyOrder({
    "name",
    "contact",
    "type"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OsvCredit {

    /**
     * The name to give credit to.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Contact methods (URLs).
     */
    @JsonProperty("contact")
    protected List<String> contact;

    @JsonProperty("type")
    protected String type;

    /**
     * Constructs a validated instance of {@link OsvCredit}.
     *
     * @param spec the specification to process
     */
    public OsvCredit(Consumer<OsvCredit> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected OsvCredit() {
    }

    /**
     * Constructs a validated instance of {@link OsvCredit}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OsvCredit(Consumer)} instead.
     * @param name The name to give credit to.
     * @param contact Contact methods (URLs).
     * @param type type
     */
    @ApiStatus.Internal
    public OsvCredit(String name, List<String> contact, String type) {
        this.name = name;
        this.contact = contact;
        this.type = type;
    }


    /**
     * Fluent getter for name.
     * <p>
     * The name to give credit to.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name to give credit to.
     *
     * @param name name
     * @return this
     */
    public OsvCredit name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name to give credit to.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name to give credit to.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for contact.
     * <p>
     * Contact methods (URLs).
     *
     * @return contact
     */
    public List<String> contact() {
        return this.contact;
    }

    /**
     * Fluent setter for contact.
     * <p>
     * Contact methods (URLs).
     *
     * @param contact contact
     * @return this
     */
    public OsvCredit contact(List<String> contact) {
        this.contact = contact;
        return this;
    }

    /**
     * Gets the value of contact.
     * <p>
     * Contact methods (URLs).
     *
     * @return contact
     */
    @JsonProperty("contact")
    public List<String> getContact() {
        return this.contact;
    }

    /**
     * Sets the value of contact.
     * <p>
     * Contact methods (URLs).
     *
     * @param contact contact
     */
    public void setContact(List<String> contact) {
        this.contact = contact;
    }
    /**
     * Fluent getter for type.
     *
     * @return type
     */
    public String type() {
        return this.type;
    }

    /**
     * Fluent setter for type.
     *
     * @param type type
     * @return this
     */
    public OsvCredit type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Gets the value of type.
     *
     * @return type
     */
    @JsonProperty("type")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of type.
     *
     * @param type type
     */
    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OsvCredit that = (OsvCredit) o;
        return
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.contact, that.contact) &&
            Objects.equals(this.type, that.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.name, 
            this.contact, 
            this.type
        );
    }

    @Override
    public String toString() {
        return "OsvCredit{" +
            "name=" + name + ", " + 
            "contact=" + contact + ", " + 
            "type=" + type +
            "}";
    }
}
