// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * OsvPackage
 * <p>
 * Package information and version.
 *
 */
@JsonTypeName("OsvPackage")
@JsonPropertyOrder({
    "name",
    "ecosystem",
    "purl"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OsvPackage {

    /**
     * Required. Name of the package. Should match the name used in the package
ecosystem (e.g. the npm package name). For C/C++ projects integrated in
OSS-Fuzz, this is the name used for the integration.
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Required. The ecosystem for this package. 
For the complete list of valid ecosystem names, see
&lt;https://ossf.github.io/osv-schema/#affectedpackage-field&gt;.
     */
    @JsonProperty("ecosystem")
    protected String ecosystem;

    /**
     * Optional. The package URL for this package.
     */
    @JsonProperty("purl")
    protected String purl;

    /**
     * Constructs a validated instance of {@link OsvPackage}.
     *
     * @param spec the specification to process
     */
    public OsvPackage(Consumer<OsvPackage> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected OsvPackage() {
    }

    /**
     * Constructs a validated instance of {@link OsvPackage}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OsvPackage(Consumer)} instead.
     * @param name Required. Name of the package. Should match the name used in the package
ecosystem (e.g. the npm package name). For C/C++ projects integrated in
OSS-Fuzz, this is the name used for the integration.
     * @param ecosystem Required. The ecosystem for this package. 
For the complete list of valid ecosystem names, see
&lt;https://ossf.github.io/osv-schema/#affectedpackage-field&gt;.
     * @param purl Optional. The package URL for this package.
     */
    @ApiStatus.Internal
    public OsvPackage(String name, String ecosystem, String purl) {
        this.name = name;
        this.ecosystem = ecosystem;
        this.purl = purl;
    }


    /**
     * Fluent getter for name.
     * <p>
     * Required. Name of the package. Should match the name used in the package
     * ecosystem (e.g. the npm package name). For C/C++ projects integrated in
     * OSS-Fuzz, this is the name used for the integration.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * Required. Name of the package. Should match the name used in the package
     * ecosystem (e.g. the npm package name). For C/C++ projects integrated in
     * OSS-Fuzz, this is the name used for the integration.
     *
     * @param name name
     * @return this
     */
    public OsvPackage name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * Required. Name of the package. Should match the name used in the package
     * ecosystem (e.g. the npm package name). For C/C++ projects integrated in
     * OSS-Fuzz, this is the name used for the integration.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * Required. Name of the package. Should match the name used in the package
     * ecosystem (e.g. the npm package name). For C/C++ projects integrated in
     * OSS-Fuzz, this is the name used for the integration.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for ecosystem.
     * <p>
     * Required. The ecosystem for this package. 
     * For the complete list of valid ecosystem names, see
     * &lt;https://ossf.github.io/osv-schema/#affectedpackage-field&gt;.
     *
     * @return ecosystem
     */
    public String ecosystem() {
        return this.ecosystem;
    }

    /**
     * Fluent setter for ecosystem.
     * <p>
     * Required. The ecosystem for this package. 
     * For the complete list of valid ecosystem names, see
     * &lt;https://ossf.github.io/osv-schema/#affectedpackage-field&gt;.
     *
     * @param ecosystem ecosystem
     * @return this
     */
    public OsvPackage ecosystem(String ecosystem) {
        this.ecosystem = ecosystem;
        return this;
    }

    /**
     * Gets the value of ecosystem.
     * <p>
     * Required. The ecosystem for this package. 
     * For the complete list of valid ecosystem names, see
     * &lt;https://ossf.github.io/osv-schema/#affectedpackage-field&gt;.
     *
     * @return ecosystem
     */
    @JsonProperty("ecosystem")
    public String getEcosystem() {
        return this.ecosystem;
    }

    /**
     * Sets the value of ecosystem.
     * <p>
     * Required. The ecosystem for this package. 
     * For the complete list of valid ecosystem names, see
     * &lt;https://ossf.github.io/osv-schema/#affectedpackage-field&gt;.
     *
     * @param ecosystem ecosystem
     */
    public void setEcosystem(String ecosystem) {
        this.ecosystem = ecosystem;
    }
    /**
     * Fluent getter for purl.
     * <p>
     * Optional. The package URL for this package.
     *
     * @return purl
     */
    public String purl() {
        return this.purl;
    }

    /**
     * Fluent setter for purl.
     * <p>
     * Optional. The package URL for this package.
     *
     * @param purl purl
     * @return this
     */
    public OsvPackage purl(String purl) {
        this.purl = purl;
        return this;
    }

    /**
     * Gets the value of purl.
     * <p>
     * Optional. The package URL for this package.
     *
     * @return purl
     */
    @JsonProperty("purl")
    public String getPurl() {
        return this.purl;
    }

    /**
     * Sets the value of purl.
     * <p>
     * Optional. The package URL for this package.
     *
     * @param purl purl
     */
    public void setPurl(String purl) {
        this.purl = purl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OsvPackage that = (OsvPackage) o;
        return
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.ecosystem, that.ecosystem) &&
            Objects.equals(this.purl, that.purl);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.name, 
            this.ecosystem, 
            this.purl
        );
    }

    @Override
    public String toString() {
        return "OsvPackage{" +
            "name=" + name + ", " + 
            "ecosystem=" + ecosystem + ", " + 
            "purl=" + purl +
            "}";
    }
}
