// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * OsvReference
 * <p>
 * Reference URL.
 *
 */
@JsonTypeName("OsvReference")
@JsonPropertyOrder({
    "type",
    "url"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OsvReference {

    @JsonProperty("type")
    protected String type;

    /**
     * Required. The URL.
     */
    @JsonProperty("url")
    protected String url;

    /**
     * Constructs a validated instance of {@link OsvReference}.
     *
     * @param spec the specification to process
     */
    public OsvReference(Consumer<OsvReference> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected OsvReference() {
    }

    /**
     * Constructs a validated instance of {@link OsvReference}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OsvReference(Consumer)} instead.
     * @param type type
     * @param url Required. The URL.
     */
    @ApiStatus.Internal
    public OsvReference(String type, String url) {
        this.type = type;
        this.url = url;
    }


    /**
     * Fluent getter for type.
     *
     * @return type
     */
    public String type() {
        return this.type;
    }

    /**
     * Fluent setter for type.
     *
     * @param type type
     * @return this
     */
    public OsvReference type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Gets the value of type.
     *
     * @return type
     */
    @JsonProperty("type")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of type.
     *
     * @param type type
     */
    public void setType(String type) {
        this.type = type;
    }
    /**
     * Fluent getter for url.
     * <p>
     * Required. The URL.
     *
     * @return url
     */
    public String url() {
        return this.url;
    }

    /**
     * Fluent setter for url.
     * <p>
     * Required. The URL.
     *
     * @param url url
     * @return this
     */
    public OsvReference url(String url) {
        this.url = url;
        return this;
    }

    /**
     * Gets the value of url.
     * <p>
     * Required. The URL.
     *
     * @return url
     */
    @JsonProperty("url")
    public String getUrl() {
        return this.url;
    }

    /**
     * Sets the value of url.
     * <p>
     * Required. The URL.
     *
     * @param url url
     */
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OsvReference that = (OsvReference) o;
        return
            Objects.equals(this.type, that.type) &&
            Objects.equals(this.url, that.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.type, 
            this.url
        );
    }

    @Override
    public String toString() {
        return "OsvReference{" +
            "type=" + type + ", " + 
            "url=" + url +
            "}";
    }
}
