// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * OsvRange
 * <p>
 * Affected ranges.
 *
 */
@JsonTypeName("OsvRange")
@JsonPropertyOrder({
    "type",
    "repo",
    "events"
})
@Generated(value = "io.github.primelib.primecodegen")
public class OsvRange {

    /**
     * Type of the version information.
     */
    @JsonProperty("type")
    protected String type;

    /**
     * Required if type is GIT. The publicly accessible URL of the repo that can
be directly passed to clone commands.
     */
    @JsonProperty("repo")
    protected String repo;

    /**
     * Required. Version event information.
     */
    @JsonProperty("events")
    protected List<OsvEvent> events;

    /**
     * Constructs a validated instance of {@link OsvRange}.
     *
     * @param spec the specification to process
     */
    public OsvRange(Consumer<OsvRange> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected OsvRange() {
    }

    /**
     * Constructs a validated instance of {@link OsvRange}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #OsvRange(Consumer)} instead.
     * @param type Type of the version information.
     * @param repo Required if type is GIT. The publicly accessible URL of the repo that can
be directly passed to clone commands.
     * @param events Required. Version event information.
     */
    @ApiStatus.Internal
    public OsvRange(String type, String repo, List<OsvEvent> events) {
        this.type = type;
        this.repo = repo;
        this.events = events;
    }


    /**
     * Fluent getter for type.
     * <p>
     * Type of the version information.
     *
     * @return type
     */
    public String type() {
        return this.type;
    }

    /**
     * Fluent setter for type.
     * <p>
     * Type of the version information.
     *
     * @param type type
     * @return this
     */
    public OsvRange type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Gets the value of type.
     * <p>
     * Type of the version information.
     *
     * @return type
     */
    @JsonProperty("type")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of type.
     * <p>
     * Type of the version information.
     *
     * @param type type
     */
    public void setType(String type) {
        this.type = type;
    }
    /**
     * Fluent getter for repo.
     * <p>
     * Required if type is GIT. The publicly accessible URL of the repo that can
     * be directly passed to clone commands.
     *
     * @return repo
     */
    public String repo() {
        return this.repo;
    }

    /**
     * Fluent setter for repo.
     * <p>
     * Required if type is GIT. The publicly accessible URL of the repo that can
     * be directly passed to clone commands.
     *
     * @param repo repo
     * @return this
     */
    public OsvRange repo(String repo) {
        this.repo = repo;
        return this;
    }

    /**
     * Gets the value of repo.
     * <p>
     * Required if type is GIT. The publicly accessible URL of the repo that can
     * be directly passed to clone commands.
     *
     * @return repo
     */
    @JsonProperty("repo")
    public String getRepo() {
        return this.repo;
    }

    /**
     * Sets the value of repo.
     * <p>
     * Required if type is GIT. The publicly accessible URL of the repo that can
     * be directly passed to clone commands.
     *
     * @param repo repo
     */
    public void setRepo(String repo) {
        this.repo = repo;
    }
    /**
     * Fluent getter for events.
     * <p>
     * Required. Version event information.
     *
     * @return events
     */
    public List<OsvEvent> events() {
        return this.events;
    }

    /**
     * Fluent setter for events.
     * <p>
     * Required. Version event information.
     *
     * @param events events
     * @return this
     */
    public OsvRange events(List<OsvEvent> events) {
        this.events = events;
        return this;
    }

    /**
     * Gets the value of events.
     * <p>
     * Required. Version event information.
     *
     * @return events
     */
    @JsonProperty("events")
    public List<OsvEvent> getEvents() {
        return this.events;
    }

    /**
     * Sets the value of events.
     * <p>
     * Required. Version event information.
     *
     * @param events events
     */
    public void setEvents(List<OsvEvent> events) {
        this.events = events;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OsvRange that = (OsvRange) o;
        return
            Objects.equals(this.type, that.type) &&
            Objects.equals(this.repo, that.repo) &&
            Objects.equals(this.events, that.events);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.type, 
            this.repo, 
            this.events
        );
    }

    @Override
    public String toString() {
        return "OsvRange{" +
            "type=" + type + ", " + 
            "repo=" + repo + ", " + 
            "events=" + events +
            "}";
    }
}
