// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Arrays;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * ProtobufAny
 *
 */
@JsonTypeName("ProtobufAny")
@JsonPropertyOrder({
    "typeUrl",
    "value"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ProtobufAny {

    @JsonProperty("typeUrl")
    protected String typeUrl;

    @JsonProperty("value")
    protected Byte[] value;

    /**
     * Constructs a validated instance of {@link ProtobufAny}.
     *
     * @param spec the specification to process
     */
    public ProtobufAny(Consumer<ProtobufAny> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected ProtobufAny() {
    }

    /**
     * Constructs a validated instance of {@link ProtobufAny}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ProtobufAny(Consumer)} instead.
     * @param typeUrl typeUrl
     * @param value value
     */
    @ApiStatus.Internal
    public ProtobufAny(String typeUrl, Byte[] value) {
        this.typeUrl = typeUrl;
        this.value = value;
    }


    /**
     * Fluent getter for typeUrl.
     *
     * @return typeUrl
     */
    public String typeUrl() {
        return this.typeUrl;
    }

    /**
     * Fluent setter for typeUrl.
     *
     * @param typeUrl typeUrl
     * @return this
     */
    public ProtobufAny typeUrl(String typeUrl) {
        this.typeUrl = typeUrl;
        return this;
    }

    /**
     * Gets the value of typeUrl.
     *
     * @return typeUrl
     */
    @JsonProperty("typeUrl")
    public String getTypeUrl() {
        return this.typeUrl;
    }

    /**
     * Sets the value of typeUrl.
     *
     * @param typeUrl typeUrl
     */
    public void setTypeUrl(String typeUrl) {
        this.typeUrl = typeUrl;
    }
    /**
     * Fluent getter for value.
     *
     * @return value
     */
    public Byte[] value() {
        return this.value;
    }

    /**
     * Fluent setter for value.
     *
     * @param value value
     * @return this
     */
    public ProtobufAny value(Byte[] value) {
        this.value = value;
        return this;
    }

    /**
     * Gets the value of value.
     *
     * @return value
     */
    @JsonProperty("value")
    public Byte[] getValue() {
        return this.value;
    }

    /**
     * Sets the value of value.
     *
     * @param value value
     */
    public void setValue(Byte[] value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ProtobufAny that = (ProtobufAny) o;
        return
            Objects.equals(this.typeUrl, that.typeUrl) &&
            Objects.equals(this.value, that.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.typeUrl, 
            this.value
        );
    }

    @Override
    public String toString() {
        return "ProtobufAny{" +
            "typeUrl=" + typeUrl + ", " + 
            "value=" + Arrays.deepToString(this.value) +
            "}";
    }
}
