// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * V1BatchQuery
 * <p>
 * Batch query format.
 *
 */
@JsonTypeName("V1BatchQuery")
@JsonPropertyOrder({
    "queries"
})
@Generated(value = "io.github.primelib.primecodegen")
public class V1BatchQuery {

    /**
     * The queries that form this batch query.
     */
    @JsonProperty("queries")
    protected List<V1Query> queries;

    /**
     * Constructs a validated instance of {@link V1BatchQuery}.
     *
     * @param spec the specification to process
     */
    public V1BatchQuery(Consumer<V1BatchQuery> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected V1BatchQuery() {
    }

    /**
     * Constructs a validated instance of {@link V1BatchQuery}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #V1BatchQuery(Consumer)} instead.
     * @param queries The queries that form this batch query.
     */
    @ApiStatus.Internal
    public V1BatchQuery(List<V1Query> queries) {
        this.queries = queries;
    }


    /**
     * Fluent getter for queries.
     * <p>
     * The queries that form this batch query.
     *
     * @return queries
     */
    public List<V1Query> queries() {
        return this.queries;
    }

    /**
     * Fluent setter for queries.
     * <p>
     * The queries that form this batch query.
     *
     * @param queries queries
     * @return this
     */
    public V1BatchQuery queries(List<V1Query> queries) {
        this.queries = queries;
        return this;
    }

    /**
     * Gets the value of queries.
     * <p>
     * The queries that form this batch query.
     *
     * @return queries
     */
    @JsonProperty("queries")
    public List<V1Query> getQueries() {
        return this.queries;
    }

    /**
     * Sets the value of queries.
     * <p>
     * The queries that form this batch query.
     *
     * @param queries queries
     */
    public void setQueries(List<V1Query> queries) {
        this.queries = queries;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        V1BatchQuery that = (V1BatchQuery) o;
        return
            Objects.equals(this.queries, that.queries);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.queries
        );
    }

    @Override
    public String toString() {
        return "V1BatchQuery{" +
            "queries=" + queries +
            "}";
    }
}
