// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * V1Query
 * <p>
 * Query format.
 *
 */
@JsonTypeName("V1Query")
@JsonPropertyOrder({
    "commit",
    "version",
    "packageProp",
    "pageToken"
})
@Generated(value = "io.github.primelib.primecodegen")
public class V1Query {

    /**
     * The commit hash to query for. If specified, `version` should not be set.
     */
    @JsonProperty("commit")
    protected String commit;

    /**
     * The version string to query for. A fuzzy match is done against upstream
versions. If specified, `commit` should not be set.
     */
    @JsonProperty("version")
    protected String version;

    /**
     * Package information and version.
     */
    @JsonProperty("package")
    protected OsvPackage packageProp;

    @JsonProperty("pageToken")
    protected String pageToken;

    /**
     * Constructs a validated instance of {@link V1Query}.
     *
     * @param spec the specification to process
     */
    public V1Query(Consumer<V1Query> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected V1Query() {
    }

    /**
     * Constructs a validated instance of {@link V1Query}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #V1Query(Consumer)} instead.
     * @param commit The commit hash to query for. If specified, `version` should not be set.
     * @param version The version string to query for. A fuzzy match is done against upstream
versions. If specified, `commit` should not be set.
     * @param packageProp Package information and version.
     * @param pageToken pageToken
     */
    @ApiStatus.Internal
    public V1Query(String commit, String version, OsvPackage packageProp, String pageToken) {
        this.commit = commit;
        this.version = version;
        this.packageProp = packageProp;
        this.pageToken = pageToken;
    }


    /**
     * Fluent getter for commit.
     * <p>
     * The commit hash to query for. If specified, `version` should not be set.
     *
     * @return commit
     */
    public String commit() {
        return this.commit;
    }

    /**
     * Fluent setter for commit.
     * <p>
     * The commit hash to query for. If specified, `version` should not be set.
     *
     * @param commit commit
     * @return this
     */
    public V1Query commit(String commit) {
        this.commit = commit;
        return this;
    }

    /**
     * Gets the value of commit.
     * <p>
     * The commit hash to query for. If specified, `version` should not be set.
     *
     * @return commit
     */
    @JsonProperty("commit")
    public String getCommit() {
        return this.commit;
    }

    /**
     * Sets the value of commit.
     * <p>
     * The commit hash to query for. If specified, `version` should not be set.
     *
     * @param commit commit
     */
    public void setCommit(String commit) {
        this.commit = commit;
    }
    /**
     * Fluent getter for version.
     * <p>
     * The version string to query for. A fuzzy match is done against upstream
     * versions. If specified, `commit` should not be set.
     *
     * @return version
     */
    public String version() {
        return this.version;
    }

    /**
     * Fluent setter for version.
     * <p>
     * The version string to query for. A fuzzy match is done against upstream
     * versions. If specified, `commit` should not be set.
     *
     * @param version version
     * @return this
     */
    public V1Query version(String version) {
        this.version = version;
        return this;
    }

    /**
     * Gets the value of version.
     * <p>
     * The version string to query for. A fuzzy match is done against upstream
     * versions. If specified, `commit` should not be set.
     *
     * @return version
     */
    @JsonProperty("version")
    public String getVersion() {
        return this.version;
    }

    /**
     * Sets the value of version.
     * <p>
     * The version string to query for. A fuzzy match is done against upstream
     * versions. If specified, `commit` should not be set.
     *
     * @param version version
     */
    public void setVersion(String version) {
        this.version = version;
    }
    /**
     * Fluent getter for packageProp.
     * <p>
     * Package information and version.
     *
     * @return packageProp
     */
    public OsvPackage packageProp() {
        return this.packageProp;
    }

    /**
     * Fluent setter for packageProp.
     * <p>
     * Package information and version.
     *
     * @param packageProp packageProp
     * @return this
     */
    public V1Query packageProp(OsvPackage packageProp) {
        this.packageProp = packageProp;
        return this;
    }

    /**
     * Gets the value of packageProp.
     * <p>
     * Package information and version.
     *
     * @return packageProp
     */
    @JsonProperty("package")
    public OsvPackage getPackageProp() {
        return this.packageProp;
    }

    /**
     * Sets the value of packageProp.
     * <p>
     * Package information and version.
     *
     * @param packageProp packageProp
     */
    public void setPackageProp(OsvPackage packageProp) {
        this.packageProp = packageProp;
    }
    /**
     * Fluent getter for pageToken.
     *
     * @return pageToken
     */
    public String pageToken() {
        return this.pageToken;
    }

    /**
     * Fluent setter for pageToken.
     *
     * @param pageToken pageToken
     * @return this
     */
    public V1Query pageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
    }

    /**
     * Gets the value of pageToken.
     *
     * @return pageToken
     */
    @JsonProperty("pageToken")
    public String getPageToken() {
        return this.pageToken;
    }

    /**
     * Sets the value of pageToken.
     *
     * @param pageToken pageToken
     */
    public void setPageToken(String pageToken) {
        this.pageToken = pageToken;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        V1Query that = (V1Query) o;
        return
            Objects.equals(this.commit, that.commit) &&
            Objects.equals(this.version, that.version) &&
            Objects.equals(this.packageProp, that.packageProp) &&
            Objects.equals(this.pageToken, that.pageToken);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.commit, 
            this.version, 
            this.packageProp, 
            this.pageToken
        );
    }

    @Override
    public String toString() {
        return "V1Query{" +
            "commit=" + commit + ", " + 
            "version=" + version + ", " + 
            "packageProp=" + packageProp + ", " + 
            "pageToken=" + pageToken +
            "}";
    }
}
