// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * V1VersionQuery
 * <p>
 * The version query.
 *
 */
@JsonTypeName("V1VersionQuery")
@JsonPropertyOrder({
    "name",
    "fileHashes"
})
@Generated(value = "io.github.primelib.primecodegen")
public class V1VersionQuery {

    /**
     * The name of the dependency. Can be empty.
     */
    @JsonProperty("name")
    protected String name;

    @JsonProperty("fileHashes")
    protected List<V1FileHash> fileHashes;

    /**
     * Constructs a validated instance of {@link V1VersionQuery}.
     *
     * @param spec the specification to process
     */
    public V1VersionQuery(Consumer<V1VersionQuery> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected V1VersionQuery() {
    }

    /**
     * Constructs a validated instance of {@link V1VersionQuery}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #V1VersionQuery(Consumer)} instead.
     * @param name The name of the dependency. Can be empty.
     * @param fileHashes fileHashes
     */
    @ApiStatus.Internal
    public V1VersionQuery(String name, List<V1FileHash> fileHashes) {
        this.name = name;
        this.fileHashes = fileHashes;
    }


    /**
     * Fluent getter for name.
     * <p>
     * The name of the dependency. Can be empty.
     *
     * @return name
     */
    public String name() {
        return this.name;
    }

    /**
     * Fluent setter for name.
     * <p>
     * The name of the dependency. Can be empty.
     *
     * @param name name
     * @return this
     */
    public V1VersionQuery name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Gets the value of name.
     * <p>
     * The name of the dependency. Can be empty.
     *
     * @return name
     */
    @JsonProperty("name")
    public String getName() {
        return this.name;
    }

    /**
     * Sets the value of name.
     * <p>
     * The name of the dependency. Can be empty.
     *
     * @param name name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Fluent getter for fileHashes.
     *
     * @return fileHashes
     */
    public List<V1FileHash> fileHashes() {
        return this.fileHashes;
    }

    /**
     * Fluent setter for fileHashes.
     *
     * @param fileHashes fileHashes
     * @return this
     */
    public V1VersionQuery fileHashes(List<V1FileHash> fileHashes) {
        this.fileHashes = fileHashes;
        return this;
    }

    /**
     * Gets the value of fileHashes.
     *
     * @return fileHashes
     */
    @JsonProperty("fileHashes")
    public List<V1FileHash> getFileHashes() {
        return this.fileHashes;
    }

    /**
     * Sets the value of fileHashes.
     *
     * @param fileHashes fileHashes
     */
    public void setFileHashes(List<V1FileHash> fileHashes) {
        this.fileHashes = fileHashes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        V1VersionQuery that = (V1VersionQuery) o;
        return
            Objects.equals(this.name, that.name) &&
            Objects.equals(this.fileHashes, that.fileHashes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.name, 
            this.fileHashes
        );
    }

    @Override
    public String toString() {
        return "V1VersionQuery{" +
            "name=" + name + ", " + 
            "fileHashes=" + fileHashes +
            "}";
    }
}
