// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * V1VersionMatch
 * <p>
 * Match information for the provided VersionQuery.
 *
 */
@JsonTypeName("V1VersionMatch")
@JsonPropertyOrder({
    "score",
    "repoInfo",
    "osvIdentifier",
    "cpe23"
})
@Generated(value = "io.github.primelib.primecodegen")
public class V1VersionMatch {

    /**
     * Score in the interval (0.0, 1.0] with 1.0 being a perfect match.
     */
    @JsonProperty("score")
    protected Double score;

    @JsonProperty("repoInfo")
    protected V1VersionRepositoryInformation repoInfo;

    /**
     * Package information and version.
     */
    @JsonProperty("osvIdentifier")
    protected OsvPackage osvIdentifier;

    /**
     * CPE 2.3.
     */
    @JsonProperty("cpe23")
    protected String cpe23;

    /**
     * Constructs a validated instance of {@link V1VersionMatch}.
     *
     * @param spec the specification to process
     */
    public V1VersionMatch(Consumer<V1VersionMatch> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected V1VersionMatch() {
    }

    /**
     * Constructs a validated instance of {@link V1VersionMatch}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #V1VersionMatch(Consumer)} instead.
     * @param score Score in the interval (0.0, 1.0] with 1.0 being a perfect match.
     * @param repoInfo repoInfo
     * @param osvIdentifier Package information and version.
     * @param cpe23 CPE 2.3.
     */
    @ApiStatus.Internal
    public V1VersionMatch(Double score, V1VersionRepositoryInformation repoInfo, OsvPackage osvIdentifier, String cpe23) {
        this.score = score;
        this.repoInfo = repoInfo;
        this.osvIdentifier = osvIdentifier;
        this.cpe23 = cpe23;
    }


    /**
     * Fluent getter for score.
     * <p>
     * Score in the interval (0.0, 1.0] with 1.0 being a perfect match.
     *
     * @return score
     */
    public Double score() {
        return this.score;
    }

    /**
     * Fluent setter for score.
     * <p>
     * Score in the interval (0.0, 1.0] with 1.0 being a perfect match.
     *
     * @param score score
     * @return this
     */
    public V1VersionMatch score(Double score) {
        this.score = score;
        return this;
    }

    /**
     * Gets the value of score.
     * <p>
     * Score in the interval (0.0, 1.0] with 1.0 being a perfect match.
     *
     * @return score
     */
    @JsonProperty("score")
    public Double getScore() {
        return this.score;
    }

    /**
     * Sets the value of score.
     * <p>
     * Score in the interval (0.0, 1.0] with 1.0 being a perfect match.
     *
     * @param score score
     */
    public void setScore(Double score) {
        this.score = score;
    }
    /**
     * Fluent getter for repoInfo.
     *
     * @return repoInfo
     */
    public V1VersionRepositoryInformation repoInfo() {
        return this.repoInfo;
    }

    /**
     * Fluent setter for repoInfo.
     *
     * @param repoInfo repoInfo
     * @return this
     */
    public V1VersionMatch repoInfo(V1VersionRepositoryInformation repoInfo) {
        this.repoInfo = repoInfo;
        return this;
    }

    /**
     * Gets the value of repoInfo.
     *
     * @return repoInfo
     */
    @JsonProperty("repoInfo")
    public V1VersionRepositoryInformation getRepoInfo() {
        return this.repoInfo;
    }

    /**
     * Sets the value of repoInfo.
     *
     * @param repoInfo repoInfo
     */
    public void setRepoInfo(V1VersionRepositoryInformation repoInfo) {
        this.repoInfo = repoInfo;
    }
    /**
     * Fluent getter for osvIdentifier.
     * <p>
     * Package information and version.
     *
     * @return osvIdentifier
     */
    public OsvPackage osvIdentifier() {
        return this.osvIdentifier;
    }

    /**
     * Fluent setter for osvIdentifier.
     * <p>
     * Package information and version.
     *
     * @param osvIdentifier osvIdentifier
     * @return this
     */
    public V1VersionMatch osvIdentifier(OsvPackage osvIdentifier) {
        this.osvIdentifier = osvIdentifier;
        return this;
    }

    /**
     * Gets the value of osvIdentifier.
     * <p>
     * Package information and version.
     *
     * @return osvIdentifier
     */
    @JsonProperty("osvIdentifier")
    public OsvPackage getOsvIdentifier() {
        return this.osvIdentifier;
    }

    /**
     * Sets the value of osvIdentifier.
     * <p>
     * Package information and version.
     *
     * @param osvIdentifier osvIdentifier
     */
    public void setOsvIdentifier(OsvPackage osvIdentifier) {
        this.osvIdentifier = osvIdentifier;
    }
    /**
     * Fluent getter for cpe23.
     * <p>
     * CPE 2.3.
     *
     * @return cpe23
     */
    public String cpe23() {
        return this.cpe23;
    }

    /**
     * Fluent setter for cpe23.
     * <p>
     * CPE 2.3.
     *
     * @param cpe23 cpe23
     * @return this
     */
    public V1VersionMatch cpe23(String cpe23) {
        this.cpe23 = cpe23;
        return this;
    }

    /**
     * Gets the value of cpe23.
     * <p>
     * CPE 2.3.
     *
     * @return cpe23
     */
    @JsonProperty("cpe23")
    public String getCpe23() {
        return this.cpe23;
    }

    /**
     * Sets the value of cpe23.
     * <p>
     * CPE 2.3.
     *
     * @param cpe23 cpe23
     */
    public void setCpe23(String cpe23) {
        this.cpe23 = cpe23;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        V1VersionMatch that = (V1VersionMatch) o;
        return
            Objects.equals(this.score, that.score) &&
            Objects.equals(this.repoInfo, that.repoInfo) &&
            Objects.equals(this.osvIdentifier, that.osvIdentifier) &&
            Objects.equals(this.cpe23, that.cpe23);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.score, 
            this.repoInfo, 
            this.osvIdentifier, 
            this.cpe23
        );
    }

    @Override
    public String toString() {
        return "V1VersionMatch{" +
            "score=" + score + ", " + 
            "repoInfo=" + repoInfo + ", " + 
            "osvIdentifier=" + osvIdentifier + ", " + 
            "cpe23=" + cpe23 +
            "}";
    }
}
