// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.osv4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Arrays;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.ApiStatus;

/**
 * V1VersionRepositoryInformation
 *
 */
@JsonTypeName("V1VersionRepositoryInformation")
@JsonPropertyOrder({
    "type",
    "address",
    "commit",
    "tag",
    "version"
})
@Generated(value = "io.github.primelib.primecodegen")
public class V1VersionRepositoryInformation {

    @JsonProperty("type")
    protected String type;

    /**
     * Source address of the repository.
     */
    @JsonProperty("address")
    protected String address;

    /**
     * Commit hash.
     */
    @JsonProperty("commit")
    protected Byte[] commit;

    @JsonProperty("tag")
    protected String tag;

    @JsonProperty("version")
    protected String version;

    /**
     * Constructs a validated instance of {@link V1VersionRepositoryInformation}.
     *
     * @param spec the specification to process
     */
    public V1VersionRepositoryInformation(Consumer<V1VersionRepositoryInformation> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Protected no-args constructor for use by serialization frameworks.
     */
    @ApiStatus.Internal
    protected V1VersionRepositoryInformation() {
    }

    /**
     * Constructs a validated instance of {@link V1VersionRepositoryInformation}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #V1VersionRepositoryInformation(Consumer)} instead.
     * @param type type
     * @param address Source address of the repository.
     * @param commit Commit hash.
     * @param tag tag
     * @param version version
     */
    @ApiStatus.Internal
    public V1VersionRepositoryInformation(String type, String address, Byte[] commit, String tag, String version) {
        this.type = type;
        this.address = address;
        this.commit = commit;
        this.tag = tag;
        this.version = version;
    }


    /**
     * Fluent getter for type.
     *
     * @return type
     */
    public String type() {
        return this.type;
    }

    /**
     * Fluent setter for type.
     *
     * @param type type
     * @return this
     */
    public V1VersionRepositoryInformation type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Gets the value of type.
     *
     * @return type
     */
    @JsonProperty("type")
    public String getType() {
        return this.type;
    }

    /**
     * Sets the value of type.
     *
     * @param type type
     */
    public void setType(String type) {
        this.type = type;
    }
    /**
     * Fluent getter for address.
     * <p>
     * Source address of the repository.
     *
     * @return address
     */
    public String address() {
        return this.address;
    }

    /**
     * Fluent setter for address.
     * <p>
     * Source address of the repository.
     *
     * @param address address
     * @return this
     */
    public V1VersionRepositoryInformation address(String address) {
        this.address = address;
        return this;
    }

    /**
     * Gets the value of address.
     * <p>
     * Source address of the repository.
     *
     * @return address
     */
    @JsonProperty("address")
    public String getAddress() {
        return this.address;
    }

    /**
     * Sets the value of address.
     * <p>
     * Source address of the repository.
     *
     * @param address address
     */
    public void setAddress(String address) {
        this.address = address;
    }
    /**
     * Fluent getter for commit.
     * <p>
     * Commit hash.
     *
     * @return commit
     */
    public Byte[] commit() {
        return this.commit;
    }

    /**
     * Fluent setter for commit.
     * <p>
     * Commit hash.
     *
     * @param commit commit
     * @return this
     */
    public V1VersionRepositoryInformation commit(Byte[] commit) {
        this.commit = commit;
        return this;
    }

    /**
     * Gets the value of commit.
     * <p>
     * Commit hash.
     *
     * @return commit
     */
    @JsonProperty("commit")
    public Byte[] getCommit() {
        return this.commit;
    }

    /**
     * Sets the value of commit.
     * <p>
     * Commit hash.
     *
     * @param commit commit
     */
    public void setCommit(Byte[] commit) {
        this.commit = commit;
    }
    /**
     * Fluent getter for tag.
     *
     * @return tag
     */
    public String tag() {
        return this.tag;
    }

    /**
     * Fluent setter for tag.
     *
     * @param tag tag
     * @return this
     */
    public V1VersionRepositoryInformation tag(String tag) {
        this.tag = tag;
        return this;
    }

    /**
     * Gets the value of tag.
     *
     * @return tag
     */
    @JsonProperty("tag")
    public String getTag() {
        return this.tag;
    }

    /**
     * Sets the value of tag.
     *
     * @param tag tag
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
    /**
     * Fluent getter for version.
     *
     * @return version
     */
    public String version() {
        return this.version;
    }

    /**
     * Fluent setter for version.
     *
     * @param version version
     * @return this
     */
    public V1VersionRepositoryInformation version(String version) {
        this.version = version;
        return this;
    }

    /**
     * Gets the value of version.
     *
     * @return version
     */
    @JsonProperty("version")
    public String getVersion() {
        return this.version;
    }

    /**
     * Sets the value of version.
     *
     * @param version version
     */
    public void setVersion(String version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        V1VersionRepositoryInformation that = (V1VersionRepositoryInformation) o;
        return
            Objects.equals(this.type, that.type) &&
            Objects.equals(this.address, that.address) &&
            Objects.equals(this.commit, that.commit) &&
            Objects.equals(this.tag, that.tag) &&
            Objects.equals(this.version, that.version);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            this.type, 
            this.address, 
            this.commit, 
            this.tag, 
            this.version
        );
    }

    @Override
    public String toString() {
        return "V1VersionRepositoryInformation{" +
            "type=" + type + ", " + 
            "address=" + address + ", " + 
            "commit=" + Arrays.deepToString(this.commit) + ", " + 
            "tag=" + tag + ", " + 
            "version=" + version +
            "}";
    }
}
